# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QueuesPractice' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QueuesPractice
pod 'Firebase/Core'
pod 'FirebaseUI/Auth'
pod 'FirebaseUI/Google'


  target 'QueuesPracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QueuesPracticeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
